const path=require('path');
const HtmlWebpackPlugin=require('html-webpack-plugin');
const ExtractTextPlugin=require('extract-text-webpack-plugin');
module.exports={
    mode:'development',
    entry:'./src/main.js',
    output:{
        path:path.resolve(__dirname,'dist'),
        filename:'index.js'
    },
    devServer:{
        open:true,
        port:8866,
        //contentBase:'./dist'
    },
    module:{
        rules:[
            {
                //要运行的文件
                test:/\.(jpg|png|gif|svg)$/,
                use:[
                    {
                        loader:'url-loader',
                        options:{
                            limit:4096
                        }
                    },
                    {
                        loader:'file-loader',
                        options:{
                            name:'[name].[ext]'
                        }
                    }
                ]
            },
            {
                test:/\.css$/,
                use:['style-loader','css-loader']
            },
            {
                test:/\.js$/,
                exclude:/node_modules/,
                use:[
                    {
                        loader:'babel-loader',
                        options:{
                            presets:['env'],
                            plugins:['transform-runtime']
                        }
                    }
                ]
            }
        ]
    },
    plugins:[
        new ExtractTextPlugin('./css[name].css'),
        new HtmlWebpackPlugin({
            template:'./src/index/html'
        })
    ]
}